"""Show some test errors generated by pmock"""

from pmock import *
import unittest


class ErrorsTest(unittest.TestCase):

    def test_unsatisfied_expectation(self):
        mock = Mock()
        mock.expects(once()).method("foo")
        mock.verify()

    def test_unexpected_call(self):
        mock = Mock()
        mock.proxy().foo()

    def test_conflicting_call(self):
        mock = Mock()
        mock.expects(never()).method("foo")
        mock.proxy().foo()


if __name__ == '__main__':
    unittest.main()



    
