"""Show some test errors generated by pmock"""

import pmock
import unittest


class ErrorsTest(unittest.TestCase):

    def test_unsatisfied_expectation(self):
        mock = pmock.Mock()
        mock.expect().method("foo")
        mock.verify()

    def test_unexpected_call(self):
        mock = pmock.Mock()
        mock.proxy().foo()

    def test_conflicting_call(self):
        mock = pmock.Mock()
        mock.expect(pmock.not_called()).method("foo")
        mock.proxy().foo()


if __name__ == '__main__':
    unittest.main()



    
